Repository vim-airline/vim-airline, pull requests merged in 2020-05, with the labels that each got.

#2136 fix missing endif
  autoload/airline/extensions/vimagit.vim
Labels: bug

#2141 [add] unite and denite's config
  autoload/airline/extensions.vim
  doc/airline.txt
Labels: enhancement

#2139 Add vim-dirvish support
  autoload/airline/extensions.vim
  autoload/airline/extensions/dirvish.vim
Labels: extensions

#2143 vim-dirvish: Fixed bugs, added include guards and documentation
  CHANGELOG.md
  autoload/airline/extensions.vim
  autoload/airline/extensions/dirvish.vim
  doc/airline.txt
Labels: bug, enhancement
